In [49]:
import numpy as np


data  = np.genfromtxt("bikeSharing.csv", delimiter = ',')
print (data[0])



[ 1.      1.      0.      1.      0.      0.      6.      0.      1.
  0.24    0.2879  0.81    0.      3.     13.     16.    ]


In [50]:
data.shape

(17379, 16)

In [27]:
from numpy import genfromtxt
data = genfromtxt('bikeSharing.csv', delimiter=',')

In [28]:
data

array([[1.0000e+00, 1.0000e+00, 0.0000e+00, ..., 3.0000e+00, 1.3000e+01,
        1.6000e+01],
       [2.0000e+00, 1.0000e+00, 0.0000e+00, ..., 8.0000e+00, 3.2000e+01,
        4.0000e+01],
       [3.0000e+00, 1.0000e+00, 0.0000e+00, ..., 5.0000e+00, 2.7000e+01,
        3.2000e+01],
       ...,
       [1.7377e+04, 1.0000e+00, 1.0000e+00, ..., 7.0000e+00, 8.3000e+01,
        9.0000e+01],
       [1.7378e+04, 1.0000e+00, 1.0000e+00, ..., 1.3000e+01, 4.8000e+01,
        6.1000e+01],
       [1.7379e+04, 1.0000e+00, 1.0000e+00, ..., 1.2000e+01, 3.7000e+01,
        4.9000e+01]])

In [29]:
data.shape

(17379, 16)

In [33]:


subsetData = data[data[:,5 ] == 0]



In [36]:
subsetData.shape

(16879, 16)

In [37]:
print ("SubsetData ", np.mean(subsetData[:, 15]))


SubsetData  190.4285798921737


In [38]:

# Solution to Q1 (i)

def compareHolidays(data, holiday):
    subset = data[data[:, 5] == holiday]
    print ("\nHoliday value is ", holiday)
    print ("Total number of users ", len(subset))
    print ("Mean number of userrs ", np.mean(subset[:, 15]))




In [46]:
copyBikeData = np.copy(subsetData) 
copyBikeData[:, 9] *= 41.0

In [48]:
copyBikeData[:, 9]

array([ 9.84,  9.02,  9.02, ..., 10.66, 10.66, 10.66])

In [47]:

    
# Solution to Q1 (ii)


def normalization(bikeData):
    
    copyBikeData = np.copy(bikeData)
    
    copyBikeData[:, 9] *= 41.0
    
    print (copyBikeData[:, 9])
    
 

In [40]:
   

# Solution to Q1 (iii)

def percentageCausal(bikeData):
    
    result = bikeData[:, 13]>bikeData[:, 14]
    print ('Percentage of time where causal users > registered ', (len(bikeData[result])*100.0)/len(bikeData)) 




In [41]:



# Solution to Q1 (iv)

def averageNumRentalBikesPerCondition(data):
    
    conditions = {1:"Clear", 2:"Misty", 3:"Light Rain", 4:"Heavy Rain"}
    
    for key in conditions:
        subsetData = data[data[:,8]==key]
        print ("Mean users for weather = ", conditions[key], ": ", np.mean(subsetData[:, 15]))


In [42]:



# solution to Q1 (v)

def analyseTemp(data, minValue, maxValue):
    # the temperature values stored in the array are multiplied by 41 
    
    higherTempCondition = (data[:,9]*41)>=minValue    
    lowerTempCondition = (data[:,9]*41)<=maxValue
    
    subset = data[higherTempCondition & lowerTempCondition]

    meanValue = np.mean(subset[:, 15])
    print ("For temp in range ", minValue, "to", maxValue, "the mean number of casual users was ", meanValue)




In [43]:


def main():
    
    bikeData = np.genfromtxt("bikeSharing.csv", delimiter = ',')
    
    
    
    # Q1 (i)
    compareHolidays(bikeData, 0)
    compareHolidays(bikeData, 1)
    
    # Q1 (ii)
    normalization(bikeData)
    
    # Q1 (iii)
    percentageCausal(bikeData)
    
    # Q1 (iv)
    averageNumRentalBikesPerCondition(bikeData)
    
    # Q1 (v)
    for temp in range(1, 40, 5):
        analyseTemp(bikeData, temp, temp+4)
    
    
    
    
main()


Holiday value is  0
Total number of users  16879
Mean number of userrs  190.4285798921737

Holiday value is  1
Total number of users  500
Mean number of userrs  156.87
[ 9.84  9.02  9.02 ... 10.66 10.66 10.66]
Percentage of time where causal users > registered  1.6284020944818458
Mean users for weather =  Clear :  204.8692718829405
Mean users for weather =  Misty :  175.16549295774647
Mean users for weather =  Light Rain :  111.57928118393235
Mean users for weather =  Heavy Rain :  74.33333333333333
For temp in range  1 to 5 the mean number of casual users was  49.29545454545455
For temp in range  6 to 10 the mean number of casual users was  73.66706302021403
For temp in range  11 to 15 the mean number of casual users was  130.68177065179506
For temp in range  16 to 20 the mean number of casual users was  169.06677265500795
For temp in range  21 to 25 the mean number of casual users was  211.70007451564828
For temp in range  26 to 30 the mean number of casual users was  242.1726786907